[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
FoodWebTools = "1f540cc9-11db-4f16-ba1b-35cbaf81ff1e"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SpeciesInteractionNetworks = "49e116ef-912f-4766-9e56-896a49944adc"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
